import PDFDocument from 'pdfkit'

interface ContractData {
  clientName: string
  contractText: string
  projectScope?: string
  price: number
  startDate: string
  endDate: string
}

interface InvoiceData {
  number: string
  client: { name: string; company?: string | null; email?: string | null }
  amount: number
  dueDate: Date
  status: string
}

export async function generateContractPDF(data: ContractData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 60, size: 'A4' })
      const buffers: Buffer[] = []

      doc.on('data', (chunk) => buffers.push(chunk))
      doc.on('end', () => resolve(Buffer.concat(buffers)))
      doc.on('error', reject)

      const primaryColor = '#1d4ed8'
      const gray = '#6b7280'

      // ── Header ──────────────────────────────────────
      doc.rect(0, 0, doc.page.width, 80).fill(primaryColor)
      doc.fill('white').fontSize(22).font('Helvetica-Bold').text('SERVICE AGREEMENT', 60, 28)
      doc.fill('white').fontSize(10).font('Helvetica').text('Growwzzy Digital Marketing Agency', 60, 54)

      doc.moveDown(3)

      // ── Contract Details ─────────────────────────────
      doc.fill('#111827').fontSize(11).font('Helvetica-Bold').text('DETAILS & PARTIES', { underline: false })
      doc.moveDown(0.4)
      doc.fill(gray).font('Helvetica').fontSize(10)
      doc.text(`This Service Agreement ("Agreement") is entered into between:`)
      doc.moveDown(0.3)
      doc.fill('#111827').text(`Service Provider: Growwzzy (the "Agency")`)
      doc.fill('#111827').text(`Client: ${data.clientName}`)
      doc.moveDown(0.5)
      doc.fill(gray).text(`Contract Value: $${data.price.toLocaleString()}`)
      doc.text(`Duration: ${new Date(data.startDate).toLocaleDateString()} to ${new Date(data.endDate).toLocaleDateString()}`)

      doc.moveDown(1.5)

      // ── Contract Content ─────────────────────────────
      doc.moveDown(1.5)
      doc.fill('#111827').fontSize(11).font('Helvetica-Bold').text('AGREEMENT TERMS')
      doc.moveDown(0.4)
      doc.fill(gray).fontSize(10).font('Helvetica').text(data.contractText || data.projectScope, { 
        lineGap: 4,
        paragraphGap: 10 
      })

      doc.moveDown(3)

      // ── Signatures ────────────────────────────────────
      const sigY = doc.y
      doc.fill('#111827').fontSize(10).font('Helvetica')
      doc.text('_________________________________', 60, sigY)
      doc.text('Growwzzy (Agency Representative)', 60, sigY + 18)
      doc.fill(gray).fontSize(8).text('Signature & Date', 60, sigY + 32)

      doc.fill('#111827').fontSize(10).font('Helvetica')
      doc.text('_________________________________', 300, sigY)
      doc.text(`${data.clientName}`, 300, sigY + 18)
      doc.fill(gray).fontSize(8).text('Signature & Date', 300, sigY + 32)

      // ── Footer ───────────────────────────────────────
      const footerY = doc.page.height - 40
      doc.rect(0, footerY - 10, doc.page.width, 50).fill('#f3f4f6')
      doc.fill(gray).fontSize(8).font('Helvetica')
        .text(`Generated by Growwzzy Platform on ${new Date().toLocaleDateString()}`, 60, footerY, { align: 'center' })

      doc.end()
    } catch (error) {
      reject(error)
    }
  })
}

export async function generateInvoicePDF(data: InvoiceData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 60, size: 'A4' })
      const buffers: Buffer[] = []

      doc.on('data', (chunk) => buffers.push(chunk))
      doc.on('end', () => resolve(Buffer.concat(buffers)))
      doc.on('error', reject)

      const primaryColor = '#1d4ed8'
      const gray = '#6b7280'

      // ── Header ──────────────────────────────────────
      doc.rect(0, 0, doc.page.width, 80).fill(primaryColor)
      doc.fill('white').fontSize(26).font('Helvetica-Bold').text('INVOICE', 60, 22)
      doc.fill('white').fontSize(10).font('Helvetica').text(`#${data.number}`, 60, 52)

      // Status badge in header
      const statusX = doc.page.width - 130
      doc.fill('white').fontSize(9).font('Helvetica-Bold').text(data.status, statusX, 35)

      doc.moveDown(3)

      // ── Billed To ────────────────────────────────────
      doc.fill('#111827').fontSize(10).font('Helvetica-Bold').text('BILLED TO')
      doc.moveDown(0.3)
      doc.fill('#111827').fontSize(12).font('Helvetica-Bold').text(data.client.name)
      if (data.client.company) doc.fill(gray).fontSize(10).font('Helvetica').text(data.client.company)
      if (data.client.email) doc.fill(gray).text(data.client.email)

      // ── Invoice Info ──────────────────────────────────
      doc.fill('#111827').fontSize(10).font('Helvetica-Bold').text('INVOICE DATE', 340, 110)
      doc.fill(gray).fontSize(10).font('Helvetica').text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), 340, 124)

      doc.fill('#111827').fontSize(10).font('Helvetica-Bold').text('DUE DATE', 340, 145)
      doc.fill(gray).fontSize(10).font('Helvetica').text(new Date(data.dueDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), 340, 159)

      doc.moveDown(4)

      // ── Table Header ─────────────────────────────────
      const tableTop = doc.y
      doc.rect(60, tableTop, doc.page.width - 120, 28).fill('#f3f4f6')
      doc.fill('#374151').fontSize(9).font('Helvetica-Bold')
        .text('DESCRIPTION', 72, tableTop + 9)
        .text('AMOUNT', doc.page.width - 140, tableTop + 9)

      // ── Table Row ─────────────────────────────────────
      const rowTop = tableTop + 28
      doc.rect(60, rowTop, doc.page.width - 120, 32).stroke('#e5e7eb')
      doc.fill('#111827').fontSize(10).font('Helvetica')
        .text('Services Rendered', 72, rowTop + 10)
        .text(`$${data.amount.toLocaleString('en-US', { minimumFractionDigits: 2 })}`, doc.page.width - 140, rowTop + 10)

      // ── Total ─────────────────────────────────────────
      const totalTop = rowTop + 50
      doc.rect(360, totalTop, doc.page.width - 420, 40).fill(primaryColor)
      doc.fill('white').fontSize(12).font('Helvetica-Bold')
        .text('TOTAL DUE', 375, totalTop + 12)
        .text(`$${data.amount.toLocaleString('en-US', { minimumFractionDigits: 2 })}`, doc.page.width - 140, totalTop + 12)

      doc.moveDown(8)

      // ── Thank You ─────────────────────────────────────
      doc.fill(gray).fontSize(9).font('Helvetica')
        .text('Thank you for your business. Please remit payment by the due date.', { align: 'center' })

      // ── Footer ────────────────────────────────────────
      const footerY = doc.page.height - 50
      doc.rect(0, footerY - 10, doc.page.width, 60).fill('#f9fafb')
      doc.fill(gray).fontSize(8).text('Growwzzy Digital Marketing Agency  •  admin@growwzzy.com', 60, footerY, { align: 'center' })

      doc.end()
    } catch (error) {
      reject(error)
    }
  })
}
